name: Demo CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  APP_NAME: demo-app

jobs:
  # ---------- Runs on every branch ----------
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@4
        with:
          node-version: "22"
      - name: Show info
        run: |
          echo "APP : ${{ env.APP_NAME }}"
          echo "Repo : ${{ github.ref_name }}"
          echo "Job : ${{ github.job }}"
          echo "Runner : ${{ runner.os }} ${{ runner.architecture }}"

      - name: Run tests
        run: npm test
